CREATE TABLE IF NOT EXISTS t_payment_txn (
  payment_id varchar(255) NOT NULL,
   reference_id varchar(50),
   group_id varchar(50),
   gateway_rrn varchar(50),
   gateway_chain_id varchar(50),
   client_reference_number varchar(50),
   amount float(53),
   authorized_amount float(53),
   auth_chain_id bigint,
   gateway_id varchar(6),
   client_id varchar(50),
   order_type varchar(50),
   mgm_id varchar(50),
   mgm_token varchar(50),
   card_holder_name varchar(50),
   tender_type varchar(50),
   tender_category varchar(50),
   issuer_type varchar(50),
   currency_code varchar(50),
   last_4_digits_of_the_card varchar(50),
   billing_address_1 varchar(50),
   billing_address_2 varchar(50),
   billing_city varchar(50),
   billing_zipcode varchar(10),
   billing_state varchar(20),
   billing_country varchar(20),
   gateway_auth_code varchar(50),
   clerk_id varchar(50),
   transaction_type varchar(20),
   transaction_status varchar(50),
   gateway_reason_code varchar(5),
   gateway_reason_description varchar(500),
   gateway_response_code varchar(40),
   gateway_auth_source varchar(40),
   deferred_auth varchar(40),
   created_timestamp datetime,
   updated_timestamp datetime,
   created_by varchar(50),
   updated_by varchar(50),
   correlation_id varchar(50),
   journey_id varchar(50),
   txn_session_id varchar(50),
   card_entry_mode varchar(20),
   avs_response_code varchar(20),
   cvv_response_code varchar(20),
   dcc_flag varchar(1),
   dcc_control_number varchar(20),
   dcc_amount varchar(20),
   dcc_bin_rate varchar(20),
   dcc_bin_currency varchar(3),
   processor_status_code varchar(20),
   processor_status_message varchar(50),
   processor_auth_code varchar(20),
   auth_subtype varchar(20),
   CONSTRAINT pk_t_payment_txn PRIMARY KEY (payment_id)
)
GO