ALTER TABLE t_payment_txn ADD CONSTRAINT DF_t_payment_txn_CREATED_BY DEFAULT CURRENT_USER FOR CREATED_BY
GO
ALTER TABLE t_payment_txn ADD CONSTRAINT DF_t_payment_txn_UPDATED_BY DEFAULT CURRENT_USER FOR UPDATED_BY
GO