DECLARE @sys_usr VARCHAR(50);
SET @sys_usr = SYSTEM_USER;

UPDATE t_payment_txn SET CREATED_BY = @sys_usr WHERE CREATED_BY IS NULL
GO

DECLARE @sys_usr VARCHAR(50);
SET @sys_usr = SYSTEM_USER;

UPDATE t_payment_txn SET UPDATED_BY = @sys_usr WHERE UPDATED_BY IS NULL
GO

ALTER TABLE t_payment_txn ALTER COLUMN CREATED_BY varchar(50) NOT NULL
GO

ALTER TABLE t_payment_txn ALTER COLUMN UPDATED_BY varchar(50) NOT NULL
GO

ALTER TABLE t_payment_txn ADD CONSTRAINT DF_t_payment_txn_CREATED_BY DEFAULT SYSTEM_USER FOR CREATED_BY
GO

ALTER TABLE t_payment_txn ADD CONSTRAINT DF_t_payment_txn_UPDATED_BY DEFAULT SYSTEM_USER FOR UPDATED_BY
GO